# Numpy Basic
- 배열의 연산
- 기술 통계
- 난수 발생과 카운팅

In [2]:
# 영벡터
import numpy as np
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [3]:
# 일벡터
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [8]:
# 정방행렬
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [7]:
# 항등행렬
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# 대칭행렬
## A == A^T